default_charset = UTF-8
session.save_path = /var/lib/loopdeck/sessions
realpath_cache_size = 4096K
opcache.memory_consumption = 64
opcache.interned_strings_buffer = 8
opcache.max_accelerated_files = 20000
opcache.save_comments = 1
